const GET_ALL_SENSORS = "GET_ALL_SENSORS"
const PUT_SENSOR = "PUT_SENSOR"
const PATCH_SENSOR_NAME = "PATCH_SENSOR_NAME"
const DELETE_SENSOR = "DELETE_SENSOR"

const PUT_SENSOR_EVENT = "PUT_SENSOR_EVENT"
const DELETE_SENSOR_EVENT = "DELETE_SENSOR_EVENT"

export {
    GET_ALL_SENSORS,
    PUT_SENSOR,
    PATCH_SENSOR_NAME,
    DELETE_SENSOR,

    PUT_SENSOR_EVENT,
    DELETE_SENSOR_EVENT,
}